extends: ["spectral:oas"]

rules:
  path-params: off
  operation-operationId: off
  oas3-examples-value-or-externalValue: off
  oas3-unused-component: off
  info-contact: off
  write-email-not-e-mail:
    description: Should use email instead of e-mail in descriptions
    severity: error
    given: "$..*[?(@property === 'description')]"	
    then:
      function: pattern
      functionOptions:
        notMatch: "\\be-mail\\b"

  must-include-operation-summary:
    description: Operation summary should be included
    severity: error
    given: "$.paths.*[?( @property === 'get' || @property === 'put' || @property === 'post' || @property === 'delete' || @property === 'options' || @property === 'head' || @property === 'patch' || @property === 'trace' )]"
    then:
      - field: "summary"
        function: truthy        

  must-include-response-examples:
    description: At least one example should be included for each API response
    severity: error
    given: "$.paths..responses.*.content.*"
    then:
      - field: "example"
        function: truthy

  must-include-response-schemas:
    description: Each API response must contain a schema
    severity: error
    given: "$.paths..responses.*.content.*"
    then:
      - field: "schema"
        function: truthy

  no-empty-titles:
    description: There can be no empty titles in schemas. Removing this title field from the property will solve this issue.
    severity: error
    given: "$..[?(@.title=='')]~"
    then:
      function: pattern
      functionOptions:
        match: "example"

  must-end-field-descriptions-with-period:
    description: All field descriptions must end with a period (".").
    severity: error
    given: "$..*['properties']..['description']"
    then:
      function: pattern
      functionOptions:
        match: "^.*[.]$"

  must-end-endpoint-descriptions-with-period:
    description: All endpoint descriptions must end with a period (".").
    severity: error
    given: "$.paths.*[?( @property === 'get' || @property === 'put' || @property === 'post' || @property === 'delete' || @property === 'options' || @property === 'head' || @property === 'patch' || @property === 'trace' )].description"
    then:
      function: pattern
      functionOptions:
        match: "^.*[.]$"
