extends: ["spectral:oas"]

rules:
  path-params: off
  operation-operationId: off
  oas3-examples-value-or-externalValue: off
  oas3-unused-component: off
  info-contact: off
  write-email-not-e-mail:
    description: Should use email instead of e-mail in descriptions
    severity: error
    given: "$..*[?(@property === 'description')]"	
    then:
      function: pattern
      functionOptions:
        notMatch: "\\be-mail\\b"

  must-include-operation-summary:
    description: Operation summary should be included
    severity: error
    given: "$.paths.*[?( @property === 'get' || @property === 'put' || @property === 'post' || @property === 'delete' || @property === 'options' || @property === 'head' || @property === 'patch' || @property === 'trace' )]"
    then:
      - field: "summary"
        function: truthy        

  must-include-response-examples:
    description: At least one example should be included for each API response
    severity: error
    given: "$.paths..responses.*.content.*"
    then:
      - field: "example"
        function: truthy

  must-include-response-schemas:
    description: Each API response must contain a schema
    severity: error
    given: "$.paths..responses.*.content.*"
    then:
      - field: "schema"
        function: truthy

  no-empty-titles:
    description: There can be no empty titles in schemas. Removing this title field from the property will solve this issue. If this title is inside an example, please fill it with a valid example.
    severity: error
    given: "$..[?(@ && @.title=='')]~"
    then:
      function: pattern
      functionOptions:
        match: "example"

  summaries-should-be-in-sentence-case:
    description: All endpoint summaries should use sentence case (capitalize only the first letter).
    severity: warn
    given: "$..*[?( @property === 'summary')]"
    then:
      function: pattern
      functionOptions:
        match: "^[A-Z][a-z ]*$"

  no-empty-descriptions:
    description: No empty descriptions allowed. Make sure that this description is a valid string that does not start with a line break (\n or \r).
    severity: error
    given: "$..*[?(@property === 'description')]"
    then:
      function: pattern
      functionOptions:
        match: "^(?!\\s*$).+"

  parameters-description:
    description: Each parameter must contain a description.
    severity: error
    given: "$.paths.*.*.parameters[*]"
    then:
      field: "description"
      function: truthy

  properties-description:
    description: Each request or response body property must contain a description.
    severity: error
    given: "$..properties.*"
    then:
      field: "description"
      function: truthy

  properties-type:
    description: Each request or response body property must contain a type.
    severity: error
    given: "$..properties.*"
    then:
      field: "type"
      function: truthy

  items-description:
    description: Each request or response body array "items" property must contain a description. This rule may also be triggered due to your request schema containing a complete example. If this is the case, make sure that your request examples exist only at scalar field levels (integer, string or boolean).
    severity: error
    given: "$.[^example].items"
    then:
      field: "description"
      function: truthy

  items-type:
    description: Each request or response body array "items" property must contain a type. This rule may also be triggered due to your request schema containing a complete example. If this is the case, make sure that your request examples exist only at scalar field levels (integer, string or boolean). 
    severity: error
    given: "$.[^example].items"
    then:
      field: "type"
      function: truthy

  endpoint-permissions:
    description: Endpoint descriptions must include a "Permissions" section, with information about License Manager resources and roles.
    severity: warn
    given: "$.paths.*.*.description"
    then:
      function: pattern
      functionOptions:
        match: "## Permissions"

  must-end-descriptions-with-period:
    description: All field descriptions must end with a period (`.`).
    severity: error
    given: "$..properties.*[?(@property === 'description')]"
    then:
      function: pattern
      functionOptions:
        match: ".*\\.$"
